name: commits-best-practices

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev

jobs:
  commit-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check PR description length
      uses: ./.github/actions/check-pr-description-length
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Check commit messages in the feature branches
    #   uses: ./.github/actions/commit-checks
    #   with:
    #     baseSha: ${{ github.event.pull_request.base.sha }}
    #     headSha: ${{ github.event.pull_request.head.sha }}
  
