name: Protect Branches workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  protect-dev-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/protect-branch
      with:
        baseBranch: 'dev'
        allowedBranches: 'feature/*'
